import { CartoonCharacter } from "@/models/cartoon-character";


export const sampleCharacter: CartoonCharacter[] = [
  {
    name: "Charlotte Elizabeth Wilson",
    age: 20,
    imageURL: "/characters/character-1.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Ginevra Weasley",
    age: 18,
    imageURL: "/characters/character-2.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Ron Weasley",
    age: 15,
    imageURL: "/characters/character-3.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Foghorn Leghorn",
    age: 75,
    imageURL: "/characters/character-4.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Foghorn Leghorn",
    age: 75,
    imageURL: "/characters/character-5.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },

  {
    name: "Charlotte Elizabeth Wilson",
    age: 20,
    imageURL: "/characters/character-1.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Ginevra Weasley",
    age: 18,
    imageURL: "/characters/character-2.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Ron Weasley",
    age: 15,
    imageURL: "/characters/character-3.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Foghorn Leghorn",
    age: 75,
    imageURL: "/characters/character-4.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Foghorn Leghorn",
    age: 75,
    imageURL: "/characters/character-5.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },


  {
    name: "Charlotte Elizabeth Wilson",
    age: 20,
    imageURL: "/characters/character-1.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Ginevra Weasley",
    age: 18,
    imageURL: "/characters/character-2.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Ron Weasley",
    age: 15,
    imageURL: "/characters/character-3.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Foghorn Leghorn",
    age: 75,
    imageURL: "/characters/character-4.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  },
  {
    name: "Foghorn Leghorn",
    age: 75,
    imageURL: "/characters/character-5.png",
    isAlive: true,
    isEvil: false,
    isGood: true,
    isNeutral: false,
  }
]
